### ISSUE TITLE
While Vim starting, sometimes it rases error

### ISSUE THREAD

**Issue by kyoh86** [tennashi/ddu-source-git#3]
```
[denops] (ddu-source-git) Unhandled rejection is detected. Worker will be reloaded: NoMethodFoundError: No MessagePack-RPC method 'redrawCurrentDdu' exists
[denops]     at dispatch (https://deno.land/x/messagepack_rpc@v2.0.0/dispatcher.ts:42:13)
[denops]     at Session.#dispatch (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:244:28)
[denops]     at Session.#handleRequestMessage (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:271:53)
[denops]     at Session.#handleMessage (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:255:37)
[denops]     at Object.write (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:159:63)
[denops]     at Object.invokeCallbackFunction (internal:ext/webidl/00_webidl.js:869:18)
[denops]     at WritableStreamDefaultController.writeAlgorithm (internal:ext/web/06_streams.js:3534:16)
[denops]     at writableStreamDefaultControllerProcessWrite (internal:ext/web/06_streams.js:4045:57)
[denops]     at writableStreamDefaultControllerAdvanceQueueIfNeeded (internal:ext/web/06_streams.js:3948:7)
[denops]     at writableStreamDefaultControllerWrite (internal:ext/web/06_streams.js:4092:5)
```

It looks the `redrawCurrentDdu` may be called before the plugin loaded.
Maybe it should be called with checking the plugin has already loaded.

**Comment by kyoh86** [comment]
It may not be planned
